### ISSUE TITLE
Зависание процесса runProcess в игре Tower Defense (Ubuntu 14.04.4 LTS)

### ISSUE THREAD

**Issue by SaboteurInCave** [CSchool/AIBattle#15]
При корректном логе происходит зависание чекера в функции runProcess.

Судя по gdb, выполняется следующий код:

```
        int exited_pid = wait(&status_new);
        if (exited_pid == pid)
        {
            kill(timeout_pid, SIGKILL);
        }
        else
        {
            kill(pid, SIGKILL);
            status = 2;
        }
        wait(NULL);
        char buffer[1024];
        int z;
        while ((z = read(outputPipe[0], buffer, sizeof(buffer))) != 0)
        {
            for (int i = 0; i < z; ++i)
                output += buffer[i];
        } 
```

И происходит kill(timeout_pid, SIGKILL), а потом уход в бесконечный цикл из-за `z == -1`

[Core dump](https://www.dropbox.com/s/egddfnmmje2abr2/core.19123?dl=0)

**Comment by tsarn** [comment]
У меня редко такое происходит. GDB говорит, что твой дамп не подходит моему TowerTester (наверно архитектуры не совпадают, у меня x86_64; у дампа, похоже, i386)
Можешь глянуть https://github.com/TsarN/sistem-backend, наверно мы будем эту либу использовать для песочницы под линуксом (+она поддерживает ограничение безопасности)

**Comment by SaboteurInCave** [comment]
Да, архитектуры не совпадают, ибо на работе действительно i386.
У меня то как раз не очень редко - примерно в 40% такое зависание и происходило.

Может хотя бы добавить проверку на -1 и выводить ошибку из `errno`?

**Comment by SaboteurInCave** [comment]
Немного покапался что происходит в этом баге.
Выяснилось, что возникает вот такая ошибка:

> 24 - Too many open files

На своей системе, я пофиксил это при помощи правки `/etc/security/limits.conf`, куда добавил:

> 'user' hard nofile 65535
> 'user' soft nofile 65535

, где `'user'` - имя пользователя в системе, от чьего имени будет запускаться чекер.

Видимо, нам нужно это записать куда-нибудь?

P.S. Сейчас выложу коммит, который будет хоть как-нибудь реагировать на данную ошибку.

**Comment by tsarn** [comment]
Может проблема в чекере TowerDefence?

**Comment by SaboteurInCave** [comment]
Ну он никаких потоков и новых файлов не создает же.
А на каких у тебя играх было такое поведение?

**Comment by tsarn** [comment]
Я почти не тестил

**Comment by SaboteurInCave** [comment]
Хорошо, сейчас постараюсь потестить на остальных вариантах без этой правки.

**Comment by SaboteurInCave** [comment]
Проверил - остальные не падают, но они и не генерируют столько ходов, сколько TowerDefense.
А ещё, если смотреть на мой ulimit, который изначально выставлен в 1024, то понятно, почему оно валится: у нас максимальное количество ходов в игре - 555, и на каждый ход вызывается 2 runProcess. Итого: 555 \* 2 > 1024 - поэтому и происходит подобная ошибка.

**Comment by tsarn** [comment]
Надо форкаться при вызове runProcess

**Comment by SaboteurInCave** [comment]
Ммм, почему? Объясни поподробнее :)

**Comment by tsarn** [comment]
Не, наверно не надо. Я думаю просто где-то пайпы не закрываются и накапливается количество открытых файлов.

**Comment by tsarn** [comment]
outputPipe[0] не закрывается в процессе чекера

**Comment by SaboteurInCave** [comment]
Поправишь и добавишь к моей ветке? Я просто сегодня не совсем смогу пописать код.
